name: Deploy Spring Boot App to Azure App Services using GIT HUB My Slot Dev2

on:
 push:
  branches:
    - az_appsvc_github_cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: SetUp Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: springboot-example
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: springboot-example
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Deploy to Azure App Service dev slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: springboot-test-app
          slot-name: dev
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '/target/*.jar'

 